import psycopg
from datetime import datetime, timedelta, timezone
from zoneinfo import ZoneInfo
import os
import sys
import json
from dotenv import load_dotenv
from flask import session

load_dotenv()
def get_connection():
    return psycopg.connect(
        host=os.getenv("DB_HOST"),
        port=os.getenv("DB_PORT"),
        dbname=os.getenv("DB_NAME"),
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD")
    )
'''def get_connection():
    return psycopg.connect(os.getenv("DATABASE_URL"))'''
def init_db():
    conn = get_connection()
 
    try:
        with conn.cursor() as cursor:
 
            # =========================================================
            # SETTINGS
            # =========================================================
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS settings (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    category_name TEXT NOT NULL,
                    version INTEGER DEFAULT 1,
                    followup_text TEXT,
                    max_attempts INTEGER NOT NULL,
                    interval_minutes INTEGER NOT NULL,
                    followup_mode TEXT DEFAULT 'manual',
                    updated_at TIMESTAMPTZ NOT NULL,
                    UNIQUE(category_name, version)
                )
            """)
 
            # =========================================================
            # CATEGORY TEMPLATES
            # =========================================================
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS category_templates (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    category_name TEXT NOT NULL,
                    version INTEGER DEFAULT 1,
                    order_number INTEGER NOT NULL,
                    draft_id TEXT NOT NULL,
                    draft_subject TEXT,
                    UNIQUE(category_name, version, order_number)
                )
            """)
 
            # =========================================================
            # FOLDER SETTINGS
            # =========================================================
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS folder_settings (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    primary_folder_id TEXT,
                    secondary_folder_id TEXT
                )
            """)
 
            # =========================================================
            # FOLLOWUPS
            # =========================================================
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS followups (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id INTEGER NOT NULL
                        REFERENCES users(id) ON DELETE CASCADE,
 
                    message_id TEXT NOT NULL,
                    conversation_id TEXT NOT NULL,
                    category_name TEXT NOT NULL,
                    category_version INTEGER DEFAULT 1,
 
                    subject TEXT,
                    status TEXT NOT NULL,
                    attempt_count INTEGER DEFAULT 0,
 
                    next_followup_at TIMESTAMPTZ NOT NULL,
                    started_at TIMESTAMPTZ NOT NULL,
                    updated_at TIMESTAMPTZ NOT NULL,
 
                    last_followup_sent_at TIMESTAMPTZ,
                    last_client_reply_at TIMESTAMPTZ,
                    last_client_email TEXT,
                    original_recipients TEXT,
 
                    last_reply_subject TEXT,
                    last_reply_body TEXT,
                    last_reply_message_id TEXT,
 
                    is_unread_reply INTEGER DEFAULT 0,
                    is_ignored_reply INTEGER DEFAULT 0,
 
                    ai_draft_body TEXT,
                    ai_draft_reasoning TEXT,
                    ai_draft_status TEXT DEFAULT 'none',
                    ai_classification TEXT,
                    ai_analyzed_at TIMESTAMPTZ,
 
                    auto_followup_enabled INTEGER DEFAULT 1,
 
                    UNIQUE(user_id, conversation_id)
                )
            """)
 
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS idx_followups_user_status_next
                ON followups(user_id, status, next_followup_at)
            """)
 
            # =========================================================
            # ACTIVITY LOGS
            # =========================================================
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS activity_logs (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    conversation_id TEXT NOT NULL,
                    action TEXT NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL
                )
            """)
 
            # =========================================================
            # APPLICATIONS SNAPSHOT
            # =========================================================
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS applications_snapshot (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 
                    upload_id INTEGER,
 
                    appser_number TEXT,
                    appser_name TEXT,
                    appser_install_status TEXT,
                    so_u_sbg TEXT,
                    owner_name TEXT,
                    tech_owner_name TEXT,
                    current_installed_version TEXT,
                    vendor_name TEXT,
                    reviewer_id TEXT,
                    reviewed_date TEXT,
                    u_run_operations_focal TEXT,
                    compliance_mode TEXT DEFAULT 'FREQUENCY',
                    remediation_due_date TEXT,
                    exception_reason TEXT,
 
                    status TEXT DEFAULT 'ACTIVE',
                    created_at TIMESTAMPTZ,
 
                    UNIQUE(upload_id, appser_number)
                )
            """)
 
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS idx_snapshot_upload
                ON applications_snapshot(upload_id)
            """)
 
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS idx_snapshot_app
                ON applications_snapshot(appser_number)
            """)
 
            # =========================================================
            # APPLICATIONS RAW DATA
            # =========================================================
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS applications_raw_data (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    upload_id INTEGER,
                    appser_number TEXT,
                    row_data TEXT,
                    created_at TIMESTAMPTZ
                )
            """)
 
            # =========================================================
            # COMPARISON LOGS
            # =========================================================
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS comparison_logs (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 
                    from_upload_id INTEGER,
                    to_upload_id INTEGER,
 
                    created_at TIMESTAMPTZ,
 
                    added_count INTEGER DEFAULT 0,
                    modified_count INTEGER DEFAULT 0,
                    missing_count INTEGER DEFAULT 0,
                    master_count INTEGER DEFAULT 0,
                    target_count INTEGER DEFAULT 0
                )
            """)
 
            # =========================================================
            # COMPARISON CHANGES
            # =========================================================
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS comparison_changes (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 
                    comparison_id INTEGER,
                    appser_number TEXT,
 
                    field_name TEXT,
                    old_value TEXT,
                    new_value TEXT,
 
                    change_type TEXT,
                    approval_status TEXT DEFAULT 'PENDING',
 
                    created_at TIMESTAMPTZ,
                    row_data TEXT
                )
            """)
 
            # =========================================================
            # APPLICATION COMMENTS
            # =========================================================
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS application_comments (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 
                    appser_number TEXT,
                    upload_id INTEGER,
                    comment TEXT,
                    created_at TIMESTAMPTZ
                )
            """)
 
            # =========================================================
            # UPLOADS
            # =========================================================
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS uploads (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 
                    file_name TEXT,
                    stored_name TEXT,
                    created_at TIMESTAMPTZ,
                    file_type TEXT DEFAULT 'RAW_UPLOAD',
 
                    comparison_id INTEGER,
                    is_master INTEGER DEFAULT 0
                )
            """)
 
            # =========================================================
            # MASTER CONTROL
            # =========================================================
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS master_control (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 
                    upload_id INTEGER,
                    is_active INTEGER DEFAULT 1,
                    created_at TIMESTAMPTZ
                )
            """)
 
            # =========================================================
            # APPLICATION MAIL CONFIG
            # =========================================================
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS application_mail_config (
                    upload_id TEXT,
                    appser_number TEXT,
                    draft_id TEXT,
                    category TEXT,
 
                    PRIMARY KEY (upload_id, appser_number)
                )
            """)
 
            # =========================================================
            # ACTION TEMPLATE MAPPING
            # =========================================================
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS action_template_mapping (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 
                    recommended_action TEXT UNIQUE,
                    draft_id TEXT,
                    category_name TEXT,
                    updated_at TIMESTAMPTZ
                )
            """)
 
            # =========================================================
            # APPLICATION ANALYSIS
            # =========================================================
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS application_analysis (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 
                    upload_id INTEGER,
                    appser_number TEXT,
 
                    frequency TEXT DEFAULT '',
                    frequency_unit TEXT DEFAULT 'days',
                    comments TEXT DEFAULT '',
                    internal_status TEXT DEFAULT '',
 
                    send_mail INTEGER DEFAULT 0,
                    is_active INTEGER DEFAULT 1,
 
                    updated_at TIMESTAMPTZ,
                    last_reviewed_date TIMESTAMPTZ,
                    next_due_date TIMESTAMPTZ,
                    last_sent_at TIMESTAMPTZ,
 
                    last_draft_id TEXT,
                    last_category TEXT,
                    send_status TEXT,
                    conversation_id TEXT,
 
                    compliance_mode TEXT DEFAULT 'FREQUENCY',
                    remediation_due_date TEXT,
                    exception_reason TEXT,
 
                    vendor_status TEXT,
                    recommended_action TEXT,
                    action_status TEXT DEFAULT 'PENDING',
 
                    review_start_date TIMESTAMPTZ,
 
                    UNIQUE(upload_id, appser_number)
                )
            """)
 
            # =========================================================
            # APPLICATION MEETINGS
            # =========================================================
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS application_meetings (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 
                    upload_id INTEGER,
                    appser_number TEXT,
 
                    meeting_status TEXT DEFAULT 'SCHEDULED',
                    meeting_start TIMESTAMPTZ,
                    meeting_end TIMESTAMPTZ,
 
                    meeting_link TEXT,
                    event_id TEXT,
 
                    created_at TIMESTAMPTZ
                )
            """)
 
            # =========================================================
            # EVIDENCE UPLOADS
            # =========================================================
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS evidence_uploads (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 
                    upload_id INTEGER,
                    appser_number TEXT NOT NULL,
 
                    file_name TEXT NOT NULL,
                    file_path TEXT NOT NULL,
                    file_type TEXT,
 
                    uploaded_at TIMESTAMPTZ,
                    uploaded_by TEXT,
 
                    ocr_text TEXT,
                    extracted_json TEXT,
 
                    ai_status TEXT DEFAULT 'PENDING',
                    ai_decision TEXT,
                    ai_reasoning TEXT,
                    confidence_score REAL,
 
                    analyst_decision TEXT,
                    analyst_remarks TEXT,
                    reviewed_at TIMESTAMPTZ,
 
                    is_active INTEGER DEFAULT 1
                )
            """)
 
            # =========================================================
            # WORKSPACES
            # =========================================================
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS workspaces (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 
                    workspace_name TEXT NOT NULL UNIQUE,
                    description TEXT DEFAULT '',
                    workspace_type TEXT DEFAULT 'MANUAL',
                    status TEXT DEFAULT 'ACTIVE',
 
                    created_at TIMESTAMPTZ NOT NULL,
                    updated_at TIMESTAMPTZ NOT NULL
                )
            """)
 
            # =========================================================
            # WORKSPACE CONVERSATIONS
            # =========================================================
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS workspace_conversations (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 
                    workspace_id BIGINT NOT NULL
                        REFERENCES workspaces(id) ON DELETE CASCADE,
 
                    conversation_id TEXT NOT NULL,
                    assigned_at TIMESTAMPTZ NOT NULL,
 
                    UNIQUE(conversation_id)
                )
            """)
 
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS
                idx_workspace_conversations_workspace
                ON workspace_conversations(workspace_id)
            """)
 
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS
                idx_workspace_conversations_conversation
                ON workspace_conversations(conversation_id)
            """)
 
            # =========================================================
            # COMMIT
            # =========================================================
            conn.commit()
 
    except Exception:
        conn.rollback()
        raise
 
    finally:
        conn.close()
def get_or_create_user_from_msal(result):
    claims = result.get("id_token_claims", {})
 
    microsoft_user_id = claims.get("oid")
    email = claims.get("preferred_username")
    display_name = claims.get("name")
 
    if not microsoft_user_id:
        raise Exception("Microsoft user ID (oid) was not returned by Microsoft.")
 
    if not email:
        raise Exception("Microsoft email/username was not returned by Microsoft.")
 
    conn = get_connection()
 
    try:
        with conn.cursor() as cursor:
 
            # Check whether this Microsoft user already exists
            cursor.execute("""
                SELECT id
                FROM users
                WHERE microsoft_user_id = %s
            """, (microsoft_user_id,))
 
            row = cursor.fetchone()
 
            if row:
                user_id = row[0]
 
                # Keep profile information up to date
                cursor.execute("""
                    UPDATE users
                    SET email = %s,
                        display_name = %s,
                        updated_at = NOW()
                    WHERE id = %s
                """, (
                    email,
                    display_name,
                    user_id
                ))
 
            else:
                # Create new SendTrix user
                cursor.execute("""
                    INSERT INTO users (
                        microsoft_user_id,
                        email,
                        display_name
                    )
                    VALUES (%s, %s, %s)
                    RETURNING id
                """, (
                    microsoft_user_id,
                    email,
                    display_name
                ))
 
                user_id = cursor.fetchone()[0]
 
        conn.commit()
 
        return user_id
 
    finally:
        conn.close()

def get_user_by_microsoft_id(microsoft_user_id):
    conn = get_connection()
 
    try:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT id, email, display_name
                FROM users
                WHERE microsoft_user_id = %s
            """, (microsoft_user_id,))
 
            row = cursor.fetchone()
 
            if not row:
                return None
 
            return {
                "id": row[0],
                "email": row[1],
                "display_name": row[2]
            }
 
    finally:
        conn.close()
        
def get_current_user_id():
    user_id = session.get("user_id")
 
    if not user_id:
        raise Exception("User not authenticated")
 
    return user_id